// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Test1.Models;

public partial class SchoolContext : DbContext
{
    public SchoolContext()
    {
    }

    public SchoolContext(DbContextOptions<SchoolContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentsCourse> StudentsCourses { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasMany(d => d.Curs).WithMany(p => p.Depts)
                .UsingEntity<Dictionary<string, object>>(
                    "DepartmentsCourse",
                    r => r.HasOne<Course>().WithMany().HasForeignKey("CursID"),
                    l => l.HasOne<Department>().WithMany().HasForeignKey("DeptID"),
                    j =>
                    {
                        j.HasKey("DeptID", "CursID");
                        j.ToTable("DepartmentsCourses");
                        j.HasIndex(new[] { "CursID" }, "IX_DepartmentsCourses_CursID");
                    });
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasOne(d => d.StudentSuperNavigation).WithMany(p => p.InverseStudentSuperNavigation).HasConstraintName("FK_Students_Students");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}