// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test1.Models;

[Index("DeptID", Name = "IX_Students_DeptID")]
public partial class Student
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(10)]
    public string Name { get; set; }

    public int Age { get; set; }

    [Required]
    public string Email { get; set; }

    public int DeptID { get; set; }

    public int? StudentSuper { get; set; }

    [ForeignKey("DeptID")]
    [InverseProperty("Students")]
    public virtual Department Dept { get; set; }

    [InverseProperty("StudentSuperNavigation")]
    public virtual ICollection<Student> InverseStudentSuperNavigation { get; set; } = new List<Student>();

    [ForeignKey("StudentSuper")]
    [InverseProperty("InverseStudentSuperNavigation")]
    public virtual Student StudentSuperNavigation { get; set; }

    [InverseProperty("Std")]
    public virtual ICollection<StudentsCourse> StudentsCourses { get; set; } = new List<StudentsCourse>();
}