// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test1.Models;

public partial class Course
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(20)]
    public string Name { get; set; }

    [Required]
    public string Description { get; set; }

    public int Duration { get; set; }

    [InverseProperty("Curs")]
    public virtual ICollection<StudentsCourse> StudentsCourses { get; set; } = new List<StudentsCourse>();

    [ForeignKey("CursID")]
    [InverseProperty("Curs")]
    public virtual ICollection<Department> Depts { get; set; } = new List<Department>();
}