// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test1.Models;

public partial class Department
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(20)]
    public string Name { get; set; }

    public string Description { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    [ForeignKey("DeptID")]
    [InverseProperty("Depts")]
    public virtual ICollection<Course> Curs { get; set; } = new List<Course>();
}