// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Test1.Models;

[PrimaryKey("StdId", "CursID")]
[Index("CursID", Name = "IX_StudentsCourses_CursID")]
public partial class StudentsCourse
{
    [Key]
    public int StdId { get; set; }

    [Key]
    public int CursID { get; set; }

    public int Grade { get; set; }

    [ForeignKey("CursID")]
    [InverseProperty("StudentsCourses")]
    public virtual Course Curs { get; set; }

    [ForeignKey("StdId")]
    [InverseProperty("StudentsCourses")]
    public virtual Student Std { get; set; }
}